name             'install_java6'
maintainer       'prabuddha'
maintainer_email 'prabuddha.nike13@gmail.com'
license          'All rights reserved'
description      'Installs Java 6 update 45'
version          '0.1.0'