###################### Filebeat Configuration Example #########################

filebeat.config_dir: /etc/filebeat/conf.d

processors:
  - add_cloud_metadata:

output.elasticsearch:
  enabled: true
  hosts: ["http://elasticsearch:9200"]
  #ssl.verification_mode: none
  #username:
  #password:


# Set to true to enable the monitoring reporter.
#xpack.monitoring.enabled: true
#xpack.monitoring.elasticsearch:
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

